# Generated by Django 6.0.2 on 2026-02-21 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('idPelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('namaPelanggan', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('passwordHash', models.CharField(max_length=128)),
                ('namaBank', models.CharField(blank=True, max_length=50)),
                ('nomorRekening', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'Pelanggan',
                'verbose_name_plural': 'Pelanggan',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('idProduk', models.AutoField(primary_key=True, serialize=False)),
                ('namaProduk', models.CharField(max_length=100)),
                ('hargaProduk', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('deskripsi', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produk/')),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('idTransaksi', models.AutoField(primary_key=True, serialize=False)),
                ('tanggalTransaksi', models.DateTimeField(auto_now_add=True)),
                ('alamatPengiriman', models.TextField()),
                ('status', models.CharField(choices=[('MENUNGGU_VERIFIKASI', 'Menunggu Verifikasi'), ('DISETUJUI', 'Disetujui'), ('DIKIRIM', 'Dikirim'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan'), ('REFUND_SELESAI', 'Refund Selesai')], max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('buktiBayar', models.ImageField(blank=True, null=True, upload_to='bukti_bayar/')),
                ('tanggalVerifikasi', models.DateTimeField(blank=True, null=True)),
                ('catatanPembayaran', models.TextField(blank=True)),
                ('buktiSampai', models.ImageField(blank=True, null=True, upload_to='bukti_sampai/')),
                ('bankRefund', models.CharField(blank=True, max_length=50)),
                ('rekeningRefund', models.CharField(blank=True, max_length=40)),
                ('buktiRefund', models.ImageField(blank=True, null=True, upload_to='bukti_refund/')),
                ('tanggalRefund', models.DateTimeField(blank=True, null=True)),
                ('catatanRefund', models.TextField(blank=True)),
                ('totalTransaksi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('idPelanggan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaksi_set', to='core.pelanggan')),
            ],
            options={
                'verbose_name': 'Transaksi',
                'verbose_name_plural': 'Transaksi',
            },
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('idDetail', models.AutoField(primary_key=True, serialize=False)),
                ('jumlahProduk', models.PositiveIntegerField()),
                ('hargaSatuanSaatTransaksi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subTotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('idProduk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produk')),
                ('idTransaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_set', to='core.transaksi')),
            ],
            options={
                'verbose_name': 'Detail Transaksi',
                'verbose_name_plural': 'Detail Transaksi',
            },
        ),
    ]
