# Generated by Django 6.0.2 on 2026-02-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtransaksi',
            name='hargaSatuanSaatTransaksi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='status',
            field=models.CharField(choices=[('MENUNGGU_VERIFIKASI', 'Menunggu Verifikasi'), ('DISETUJUI', 'Disetujui'), ('DIKIRIM', 'Dikirim'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan'), ('REFUND_SELESAI', 'Refund Selesai')], default='MENUNGGU_VERIFIKASI', max_length=20),
        ),
    ]
