# Generated by Django 6.0.2 on 2026-02-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_detailtransaksi_hargasatuansaattransaksi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtransaksi',
            name='idProduk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produk'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='idPelanggan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_set', to='core.pelanggan'),
        ),
    ]
