# Generated by Django 4.2.11 on 2026-03-01 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_detailtransaksi_idproduk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurir',
            fields=[
                ('idKurir', models.AutoField(primary_key=True, serialize=False)),
                ('namaKurir', models.CharField(max_length=100)),
                ('noHp', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('passwordHash', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Kurir',
                'verbose_name_plural': 'Kurir',
            },
        ),
        migrations.AddField(
            model_name='transaksi',
            name='idKurir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_set', to='core.kurir'),
        ),
    ]
