# Generated by Django 4.2.11 on 2026-03-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_kurir_transaksi_idkurir'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='ongkir',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
