# Generated by Django 4.2.11 on 2026-03-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaksi_ongkir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurir',
            name='namaKurir',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='namaPelanggan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='produk',
            name='namaProduk',
            field=models.CharField(max_length=50),
        ),
    ]
