# Generated by Django 4.2.11 on 2026-04-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_kurir_namakurir_alter_pelanggan_namapelanggan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelanggan',
            name='namaBank',
        ),
        migrations.RemoveField(
            model_name='pelanggan',
            name='nomorRekening',
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='nomorTelepon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
