# Generated by Django 4.2.11 on 2026-07-30 23:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_pelanggan_namabank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='ongkir',
            field=models.DecimalField(choices=[(Decimal('0'), 'Rp. 0'), (Decimal('5000'), 'Rp. 5.000'), (Decimal('10000'), 'Rp. 10.000'), (Decimal('15000'), 'Rp. 15.000'), (Decimal('20000'), 'Rp. 20.000'), (Decimal('25000'), 'Rp. 25.000'), (Decimal('30000'), 'Rp. 30.000'), (Decimal('35000'), 'Rp. 35.000'), (Decimal('40000'), 'Rp. 40.000'), (Decimal('45000'), 'Rp. 45.000'), (Decimal('50000'), 'Rp. 50.000'), (Decimal('55000'), 'Rp. 55.000'), (Decimal('60000'), 'Rp. 60.000'), (Decimal('65000'), 'Rp. 65.000'), (Decimal('70000'), 'Rp. 70.000'), (Decimal('75000'), 'Rp. 75.000'), (Decimal('80000'), 'Rp. 80.000'), (Decimal('85000'), 'Rp. 85.000'), (Decimal('90000'), 'Rp. 90.000'), (Decimal('95000'), 'Rp. 95.000'), (Decimal('100000'), 'Rp. 100.000')], decimal_places=2, default=0, max_digits=12),
        ),
    ]
