"""
Django settings for MorningGloryFlorist project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rl_6dnkf39yjsjor1)w%lau@z_lj3(wg6@gb^q)!!z)pbol33x'

# SECURITY WARNING: don't run with debug turned on in production!
# Untuk production di PythonAnywhere, set DEBUG = False
# Untuk sementara testing awal, boleh set DEBUG = True dulu
# lalu ganti ke False setelah semua berjalan normal
DEBUG = False

ALLOWED_HOSTS = [
    'coderNTT4.pythonanywhere.com',
    'localhost',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MorningGloryFlorist.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MorningGloryFlorist.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = '/static/'

# STATICFILES_DIRS dikosongkan karena semua aset sudah dipindahkan ke
# core/static/img/ — Django akan otomatis menemukannya via APP_DIRS (AppDirectoriesFinder)
# karena app 'core' terdaftar di INSTALLED_APPS.
STATICFILES_DIRS = []

# Folder tujuan collectstatic untuk production (PythonAnywhere)
# Path absolut: /home/coderNTT4/MorningGloryFlorist/staticfiles
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (upload pengguna: foto produk, bukti bayar, dll)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

JAZZMIN_SETTINGS = {
    "site_title": "Morning Glory Florist",
    "site_header": "Morning Glory Florist",
    "site_brand": "Morning Glory Florist",
    # Jazzmin mencari logo relatif terhadap folder STATIC_ROOT setelah collectstatic.
    # Pastikan file logo.png ada di: static/img/logo.png (di root project)
    # lalu jalankan: python manage.py collectstatic
    # Hasilnya akan ada di: staticfiles/img/logo.png — itulah yang dibaca Jazzmin.
    "site_logo": "img/logo.png",
    "login_logo": "img/logo.png",
    "login_form_url": "",
    "copyright": "Morning Glory Florist",
    "footer_text": "Morning Glory Florist",
    "show_ui_builder": False,
    "custom_links": {
        "core": [
            {
                "name": "Laporan Penjualan",
                "url": "laporan_penjualan",
                "icon": "fa-solid fa-file-invoice-dollar",
                "permissions": ["auth.view_user"]
            },
            {
                "name": "Laporan Produk",
                "url": "laporan_produk",
                "icon": "fa-solid fa-boxes-stacked",
                "permissions": ["auth.view_user"]
            },
            {
                "name": "Laporan Pelanggan",
                "url": "laporan_pelanggan",
                "icon": "fa-solid fa-users",
                "permissions": ["auth.view_user"]
            },
        ]
    },
    "icons": {
        "core.Pelanggan": "fa-solid fa-user",
        "core.Produk": "fa-solid fa-box",
        "core.Transaksi": "fa-solid fa-receipt",
        "core.Kurir": "fa-solid fa-motorcycle",
        "auth.user": "fa-solid fa-users",
        "auth.Group": "fa-solid fa-layer-group",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-navy",
    "navbar": "navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-warning",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cosmo",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "navbar_color": "primary",
    "navbar_style": "dark",
    "sidebar_color": "primary",
    "sidebar_style": "dark",
    "sidebar_nav_header_color": "primary",
    "fixed_sidebar": True,
    "fixed_navbar": True,
    "box_supports_dark_mode": True
}
